import { readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { join, extname, basename, dirname } from "node:path";

export type GalleryImage = { src: string; alt: string; filename: string };
export type GalleryCategory = { category: string; images: GalleryImage[] };

const IMAGE_EXTS = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);

const CATEGORY_LABELS: Record<string, string> = {
  apparel: "Custom apparel",
  drinkware: "Custom drinkware",
  signs: "Custom sign or decor piece",
  gifts: "Custom gift or promo item",
  commissions: "Personal commission",
};

function humanize(filename: string): string {
  const stem = basename(filename, extname(filename));
  return stem.replace(/^placeholder-/, "").replace(/[-_]+/g, " ").trim();
}

export function buildManifest(galleryRoot: string): GalleryCategory[] {
  const categories = readdirSync(galleryRoot)
    .filter((entry) => {
      const full = join(galleryRoot, entry);
      return !entry.startsWith(".") && statSync(full).isDirectory();
    })
    .sort();

  return categories.map((category): GalleryCategory => {
    const dir = join(galleryRoot, category);
    const images = readdirSync(dir)
      .filter((file) => !file.startsWith(".") && IMAGE_EXTS.has(extname(file).toLowerCase()))
      .sort()
      .map<GalleryImage>((filename) => ({
        src: `/gallery/${category}/${filename}`,
        alt: `${CATEGORY_LABELS[category] ?? category} — ${humanize(filename)}`,
        filename,
      }));
    return { category, images };
  });
}

export function writeManifest(galleryRoot: string, outFile: string): void {
  const manifest = buildManifest(galleryRoot);
  mkdirSync(dirname(outFile), { recursive: true });
  const body =
    `// AUTO-GENERATED by scripts/generate-gallery-manifest.ts — do not edit by hand.\n` +
    `import type { GalleryCategory } from "../../scripts/generate-gallery-manifest";\n` +
    `export const GALLERY: GalleryCategory[] = ${JSON.stringify(manifest, null, 2)};\n`;
  writeFileSync(outFile, body);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const root = join(process.cwd(), "public", "gallery");
  const out = join(process.cwd(), "src", "data", "gallery.generated.ts");
  writeManifest(root, out);
  console.log(`Gallery manifest written to ${out}`);
}
